[workspace]
resolver = "2"

members = [
    "aoc_starter",
    "aoc_22_01",
    "aoc_22_02",
    "aoc_22_03",
    "aoc_22_04",
    "aoc_22_05",
    "aoc_23_01",
    "aoc_23_02",
    "aoc_23_03",
    "aoc_23_04"
]