/* use aoc_22_01;
use aoc_22_02;
use aoc_22_03;
use aoc_22_04;
use aoc_22_05;
use aoc_22_06;
use aoc_22_07;
use aoc_23_01;
use aoc_23_02;
use aoc_23_03;
use aoc_23_04;
use aoc_23_05;
use aoc_23_06;
use aoc_23_07;
use aoc_23_08; */
use aoc_23_09;

fn main() {
/*     println!("--------------------");
    println!("Running aoc_22_01...");
    println!("--------------------");
    aoc_22_01::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_02...");
    println!("--------------------");
    aoc_22_02::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_03...");
    println!("--------------------");
    aoc_22_03::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_04...");
    println!("--------------------");
    aoc_22_04::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_05...");
    println!("--------------------");
    aoc_22_05::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_06...");
    println!("--------------------");
    aoc_22_06::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_07...");
    println!("--------------------");
    aoc_22_07::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_01...");
    println!("--------------------");
    aoc_23_01::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_02...");
    println!("--------------------");
    aoc_23_02::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_03...");
    println!("--------------------");
    aoc_23_03::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_04...");
    println!("--------------------");
    aoc_23_04::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_05...");
    println!("--------------------");
    aoc_23_05::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_06...");
    println!("--------------------");
    aoc_23_06::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_07...");
    println!("--------------------");
    aoc_23_07::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_08...");
    println!("--------------------");
    aoc_23_08::start_app(); */
    println!("");
    println!("--------------------");
    println!("Running aoc_23_09...");
    println!("--------------------");
    aoc_23_09::start_app();
    println!("");
    println!("--------------------");
}
