use aoc_22_01;
use aoc_22_02;
use aoc_22_03;
use aoc_22_04;
use aoc_22_05;
use aoc_22_06;
use aoc_22_07;
use aoc_23_01;
use aoc_23_02;

fn main() {
    println!("--------------------");
    println!("Running aoc_22_01...");
    println!("--------------------");
    aoc_22_01::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_02...");
    println!("--------------------");
    aoc_22_02::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_03...");
    println!("--------------------");
    aoc_22_03::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_04...");
    println!("--------------------");
    aoc_22_04::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_05...");
    println!("--------------------");
    aoc_22_05::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_06...");
    println!("--------------------");
    aoc_22_06::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_22_07...");
    println!("--------------------");
    aoc_22_07::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_01...");
    println!("--------------------");
    aoc_23_01::start_app();
    println!("");
    println!("--------------------");
    println!("Running aoc_23_02...");
    println!("--------------------");
    aoc_23_02::start_app();
    println!("");
    println!("--------------------");
}
